// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_mastery;

namespace api_mastery.Migrations
{
    [DbContext(typeof(DogBreedContext))]
    [Migration("20190331012342_AddDogGroupModel")]
    partial class AddDogGroupModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api_mastery.Models.DogBreed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DogBreedImg");

                    b.Property<string>("DogBreedName");

                    b.Property<int>("GroupId");

                    b.HasKey("Id");

                    b.ToTable("DogBreeds");

                    b.HasData(
                        new { Id = 1, DogBreedImg = "/Images/.jpg", DogBreedName = "Husky", GroupId = 0 },
                        new { Id = 2, DogBreedImg = "/Images/.jpg", DogBreedName = "Lab", GroupId = 0 },
                        new { Id = 3, DogBreedImg = "/Images/.jpg", DogBreedName = "Great Dane", GroupId = 0 }
                    );
                });

            modelBuilder.Entity("api_mastery.Models.DogGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DogGroupImg");

                    b.HasKey("Id");

                    b.ToTable("DogGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
