// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_mastery;

namespace api_mastery.Migrations
{
    [DbContext(typeof(DogBreedContext))]
    [Migration("20190331014610_addPrivateKey")]
    partial class addPrivateKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api_mastery.Models.DogBreed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DogBreedImg");

                    b.Property<string>("DogBreedName");

                    b.Property<int>("GroupId");

                    b.HasKey("Id");

                    b.ToTable("DogBreeds");

                    b.HasData(
                        new { Id = 1, DogBreedImg = "/Images/.jpg", DogBreedName = "Husky", GroupId = 1 },
                        new { Id = 2, DogBreedImg = "/Images/.jpg", DogBreedName = "BloodHound", GroupId = 2 },
                        new { Id = 3, DogBreedImg = "/Images/.jpg", DogBreedName = "German Shepherd", GroupId = 3 }
                    );
                });

            modelBuilder.Entity("api_mastery.Models.DogGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DogGroupImg");

                    b.Property<string>("DogGroupName");

                    b.HasKey("Id");

                    b.ToTable("DogGroups");

                    b.HasData(
                        new { Id = 1, DogGroupImg = "/Images/working-group.jpg", DogGroupName = "Working" },
                        new { Id = 2, DogGroupImg = "/Images/Hounds_group.jpg", DogGroupName = "Hound" },
                        new { Id = 3, DogGroupImg = "/Images/working-group.jpg", DogGroupName = "Herding" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
